### ISSUE TITLE
caffe_copy(int, float*, double*) does not exist

### ISSUE THREAD

**Issue by amonszpart** [lmb-freiburg/optical-flow-2d-data-generation#1]
Hi,

Neat method!

I've almost got it to compile with Caffe `v1.0` or `master`, but am getting stuck on the fact, that `CImg` yields a `float*` array as output, and `Dtype` seems to be double in some scenarios, which makes this call cause a compilation error:

https://github.com/lmb-freiburg/optical-flow-2d-data-generation/blob/4d1ab7999c5a4c487f65e8ac72b2c13d921c0cbe/src/caffe/layers/data_generation_layer.cpp#L242-L244

How did you overcome this?

Thanks,
Aron

**Comment by nikolausmayer** [comment]
Hi,

I believe I changed the central typedefs for testing in `include/caffe/test/test_caffe_main.hpp`, e.g.
`typedef ::testing::Types<float, double> TestDtypes;` 
to only `<float>`. I can't say for sure, but I think only the testing framework instantiates everything to `double`.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
